Move version to nspanel_esphome_core_versioning.yaml

diff --git a/.github/workflows/validate_esphome.yml b/.github/workflows/validate_esphome.yml
--- a/.github/workflows/validate_esphome.yml
+++ b/.github/workflows/validate_esphome.yml
@@ -49,9 +49,14 @@ jobs:
         id: extract_version
         run: |
           # Extract the version and remove leading/trailing spaces
-          VERSION=$(grep "version:" esphome/nspanel_esphome_core.yaml | sed 's/version: //' | xargs)
+          VERSION=$(grep "version:" esphome/nspanel_esphome_core_versioning.yaml | sed 's/version: //' | xargs)
+          if [ -z "$VERSION" ]; then
+            echo "Error: No version found in esphome/nspanel_esphome_core_versioning.yaml"
+            exit 1
+          fi
           echo "Extracted Version: ${VERSION}"
           echo "version=${VERSION}" >> $GITHUB_OUTPUT
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV # Explicitly set the environment variable to verify
 
       - name: Cache ESP-IDF v4 Dependencies
         id: cache-idf-v4
@@ -367,6 +372,15 @@ jobs:
     if: contains(github.ref, 'dev') || contains(github.base_ref, 'dev')
     steps:
       - uses: actions/checkout@main
+
+      - name: Debug Version Output
+        run: |
+          echo "Version from setup_dependencies: ${{ needs.setup_dependencies.outputs.version }}"
+          echo "Environment Variable VERSION: $VERSION"
+          if [ -z "${{ needs.setup_dependencies.outputs.version }}" ]; then
+            echo "Error: Version output is empty. Exiting..."
+            exit 1
+          fi
 
       - name: Build ESPHome Prebuilt Firmware
         id: build_nspanel_fw
