Move version extract to prebuild job

diff --git a/.github/workflows/validate_esphome.yml b/.github/workflows/validate_esphome.yml
--- a/.github/workflows/validate_esphome.yml
+++ b/.github/workflows/validate_esphome.yml
@@ -36,7 +36,6 @@ jobs:
     name: Setup & Cache Dependencies
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.extract_version.outputs.version }}
       cache-hit-idf-v4: ${{ steps.cache-idf-v4.outputs.cache-hit }}
       cache-hit-idf-v5: ${{ steps.cache-idf-v5.outputs.cache-hit }}
       cache-hit-arduino: ${{ steps.cache-arduino.outputs.cache-hit }}
@@ -45,19 +44,6 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@main
 
-      - name: Extract Version Number
-        id: extract_version
-        run: |
-          # Extract the version from the YAML file more accurately
-          VERSION=$(yq eval '.substitutions.version' esphome/nspanel_esphome_core_versioning.yaml)
-          if [ -z "$VERSION" ]; then
-            echo "Error: No version found in esphome/nspanel_esphome_core_versioning.yaml"
-            exit 1
-          fi
-          echo "Extracted Version: ${VERSION}"
-          echo "version=${VERSION}" >> $GITHUB_OUTPUT
-          echo "VERSION=${VERSION}" >> $GITHUB_ENV
-      
       - name: Cache ESP-IDF v4 Dependencies
         id: cache-idf-v4
         uses: actions/cache@main
@@ -373,11 +359,23 @@ jobs:
     steps:
       - uses: actions/checkout@main
 
+      - name: Extract Version Number
+        id: extract_version
+        run: |
+          VERSION=$(yq eval '.substitutions.version' esphome/nspanel_esphome_core_versioning.yaml)
+          if [ -z "$VERSION" ]; then
+            echo "Error: No version found in esphome/nspanel_esphome_core_versioning.yaml"
+            exit 1
+          fi
+          echo "Extracted Version: ${VERSION}"
+          echo "version=${VERSION}" >> $GITHUB_OUTPUT
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+      
       - name: Debug Version Output
         run: |
-          echo "Version from setup_dependencies: ${{ needs.setup_dependencies.outputs.version }}"
+          echo "Version from setup_dependencies: ${{ steps.extract_version.outputs.version }}"
           echo "Environment Variable VERSION: $VERSION"
-          if [ -z "${{ needs.setup_dependencies.outputs.version }}" ]; then
+          if [ -z "${{ steps.extract_version.outputs.version }}" ]; then
             echo "Error: Version output is empty. Exiting..."
             exit 1
           fi
@@ -400,7 +398,7 @@ jobs:
         with:
           file: ${{ steps.build_nspanel_fw.outputs.name }}/manifest.json
           field: version
-          value: ${{ needs.setup_dependencies.outputs.version }}
+          value: ${{ steps.extract_version.outputs.version }}
 
       - name: Update manifest.json - builds.chipFamily
         uses: jossef/action-set-json-field@v2.2
@@ -421,7 +419,7 @@ jobs:
         with:
           file: ${{ steps.build_nspanel_fw.outputs.name }}/manifest.json
           field: builds.ota.release_url
-          value: "https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v${{ needs.setup_dependencies.outputs.version }}"
+          value: "https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v${{ steps.extract_version.outputs.version }}"
 
       - name: Move and Rename Firmware File - nspanel_esphome_prebuilt
         run: |
@@ -449,7 +447,7 @@ jobs:
         with:
           file: ${{ steps.build_wall_display_fw.outputs.name }}/manifest.json
           field: version
-          value: ${{ needs.setup_dependencies.outputs.version }}
+          value: ${{ steps.extract_version.outputs.version }}
 
       - name: Update manifest.json - builds.chipFamily
         uses: jossef/action-set-json-field@v2.2
@@ -470,7 +468,7 @@ jobs:
         with:
           file: ${{ steps.build_wall_display_fw.outputs.name }}/manifest.json
           field: builds.ota.release_url
-          value: "https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v${{ needs.setup_dependencies.outputs.version }}"
+          value: "https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v${{ steps.extract_version.outputs.version }}"
 
       - name: Move and Rename Firmware File - wall_display
         run: |
